### PR TITLE
Binary operator resolution and implicit type conversions

### PR DESCRIPTION
**Pull request by rafalcieslak**
This branch introduces initial support for implicit conversions.

I don't want to merge it just yet, I want you to review and see how do you like my solution. In particular, I am very unsure about my changes to Proxy (I don't get the nature of it!). I am also interested in how do you feel about my approach to extract type-resolution related code to a `TypeMatcher` class. Generally, let's merge it once we are both happy with this implementation.

This branch should enable us to perform implicit conversions. `./examples/implicit.cco` provides a simple testcase. Turns out currently we only have on kind of implicit conversion - that is int->double (I really dislike implicit boolean conversions). Adding new ones is as simple as providing a new entry to `TypeMatcher::InitImplicitConversions()`. The conversions can be performed with a llvm instruction, or, potentially, with a runtime library call (for complex types), and it should be just as simple!

What still needs to be done:
- Function overload resolution will use exactly the same logic as operator resolution, just slightly more generalized to more than 2 arguments. I cannot implement it just yet, as we do not use name-mangling yet.
- Transitive implicit conversions (eg. int->float->double) are unimplemented. I believe it's simple to add, though - turning map-lookup in `TypeMatcher::Inflate` into Dijkstra algorithm should be enough. No way to test it, though, until we have more conversions.
- The error displayed on multiple candidates match should be more verbose, but I cannot test it as we do not have enough types.

Note: maybe we might implement a `complex` number type. That would introduce some extra implicit conversions, and would provide a non-trivial type that is not represented by llvm and requires runtime library support for operations. Just a thought.

### CODE REVIEW

**Comment by rafalcieslak** [comment]
With the latest changes, transitive implicit conversions are supported. All variable occurences now start as a reference type (and can be implicitly converted to their value type). Implicit conversions are also possible at assignment and return statements.

**Comment by rafalcieslak** [comment]
With the recent change adding implicit conversions for arguments of function calls, all examples compile and run correctly. Also at this point adding function overloading and resolution should be a piece of cake.

**Comment by rafalcieslak** [comment]
I've noticed that some `ExpAST`s would perform typematching within both `codegen` and `maintype`. That is unnecessary, it is enough to resolve types once, and remember the result. I've added a `Resolvable` interface, which is used as a resolution result cache. Such expressions now call `Resolve()` (once in their lifetime), it performs the typematching - specific to each `Expr` type - and stores the result, so that `codegen` and `maintype` can use it later on.

This change also cleans the sources a bit by removing repeated code.

**Comment by socumbersome** [comment]
Phew! I have read the changes and I cannot say that I understand all the things under the hood of `TypeMatcher`, but I hope I at least understand how it is used.

One thing worries me a bit, namely, we might have lost a nice separation of functionality somewhere -- that is, I would really like to think that our compiler works as follows:
1. Parse input and produce initial ASTs
2. Typecheck ASTs -- during this phase, add conversions if types say so (`conversions` in the sense of some additional AST nodes squeezed here and there)
3. Codegen resulting ASTs

In current approach, points 2. and 3. are essentially merged together, which not only breaks elegant separation (we could live with that), but also, and most importantly, would probably hinder us from performing optimizations on ASTs later on, as they wouldn't have been typechecked before. And mind you, it's not just an argument that information from typechecker might be useful in devising good optimizations, but that would mean optimizing malformed programs (if there is no load of a variable in a place where it should be, I consider such program (or AST representing it) malformed). I fear it would lead to some disaster ;)

I think it's a good moment to gather up all the ideas for `TODO`s and define tasks as separate issues to tidy up this conversation a bit (and make tracking them easier). So here they go -- some from you and some from me:
- Medium(?) sized refactoring to separate typechecking from codegenning
- Implement `Complex` in-built type along with possible conversions to it
- The error displayed on multiple candidates match should be more verbose
- Get rid of `BinaryExprAST` and treat all operators just as functions (I'm not sure if this one is sane :)) -- this also means implementing name mangling (which should be plain simple, e.g. `$funname$rett$argt1$argt2$`). But as far as I see, name mangling is necessary only when lowering to LLVM and in `real` code we don't need it at all. It's the same as for operators that just have `Opcode`s that are not unique but we codegen different versions depending on the chosen overload.

**Pull request merged**
